build:
    environment:
        php:
            version: 7.0
    dependencies:
        before:
            - composer self-update
            - composer global require "fxp/composer-asset-plugin:^1.2.0" --no-interaction
        override:
            - composer install --prefer-source
    tests:
        override:
            - phpunit --testsuite=unit
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php:
        code_rating: true
        duplication: false
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
coding_style:
    php:
        spaces:
            around_operators:
                negation: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            constants:
                true_false_null: lower
