language: php

php:
  - "5.6"
  - "5.5"

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require --no-progress "fxp/composer-asset-plugin:^1.1"
  - travis_retry composer install --prefer-source --no-interaction --no-progress

